# Generated by Django 4.2.1 on 2023-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groceryapp', '0003_rename_user_usercustom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
