# Generated by Django 4.2.1 on 2023-07-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groceryapp', '0004_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
